config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'sessions#login'
  #user route
  resources :users,only: [:new,:create,:edit,:update,:show,:destroy]

  #sessions routes
  get '/login' ,to:'sessions#login'
  post '/login',to: 'sessions#create'
  post '/logout',to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'
    #root 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :body

	after_create_commit {broadcast_prepend_to :posts}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
    @post = Post.new
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path}
        format.json { render :show, status: :created, location: @post }
      else
        format.turbo_stream {render turbo_stream: turbo_stream.replace(@post,partial: 'posts/form', locals: {post: @post}) }
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :likes)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def create
		@user =User.find_by(username: params[:username])

		if !!@user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			message="welcome"
			redirect_to posts_path,notice:message
		else

			message="something go wrong"
			redirect_to login_path, notice:message
		end


	end

	def destroy
		message="Bye"
		redirect_to login_path, notice:message

	end
	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :new
		end
	end

	def show
		@user=User.find(params[:id])
	end

	private

	def user_params
		params.require(:user).permit(:username,:password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def logged_in?
		!!session[:user_id]
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :likes %>
    <%= form.number_field :likes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div style="background:lightgrey; width:300px; padding:10px;">
	<%= post.body %>
	<br>
	<%= link_to :edit, edit_post_path(post)%>
	<%= button_to "likes (#{post.likes || 0})",post_path(post,like:  true), method: :put %>
</div>
</br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>



<%= turbo_stream_from :posts %>

<%= turbo_frame_tag :post_form do %>
  <%= render 'posts/form', post: @post %>
<% end %>

<%= turbo_frame_tag :posts do %>
  <%= render @posts %>
<% end %>

<br>

<%=link_to 'bye', logout_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @post.likes %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/new.html.erb
<h1>New Users Page</h1>
<%= form_for @user do |f| %>
	<%= f.label :username %>
	<%= f.text_field :username %><br>
	<%= f.label :password %>
	<%= f.password_field :password %><br>
	<%= f.submit "Create Account" %>
<% end %>